### ISSUE TITLE
eos-bootstrap CommandError exception should include diagnostic details

### ISSUE THREAD

**Issue by jpsenior** [Apstra/aeon-ztps#58] opened 2016-09-18 20:26 UTC
If eos-bootstrap fails with a device command error, the bootstrap log entry is not helpful to understand what the root cause problem is.

Adding the command that was supposed run and the result (failure) output from the EOS device would be helpful to an administrator troubleshooting ZTP booting issues.

Example from below is from dev.api.execute('copy running-config status-config') which caused a CommandError traceback, but with no idea to the administrator as to why.

root cause:
line 252 executes 'enable' followed by 'copy running-config startup-config' to save config to reload.

To troubleshoot this I had to attach pdb to eos-bootstrap and run it manually to capture traceback details.

on vEOS my device is stuck in zerotouch mode. It hasn't rebooted.

It would have been nice to see this in the logs:
**% Cannot copy to startup-config when ZeroTouch is enabled**

```
admin@aeon-ztps:/opt/aeonztps/bin$ ./eos-bootstrap --target 172.16.60.228 --server 172.16.60.234:8080 --topdir /opt/aeonztps -U AEON_TUSER -P AEON_TPASSWD
2016-09-17 00:24:11,263:INFO:172.16.60.228:starting bootstrap process in 60 seconds


2016-09-17 00:25:11,345:INFO:172.16.60.228:reload-countdown at: 600 seconds
2016-09-17 00:25:11,450:INFO:172.16.60.228:proceeding with bootstrap
2016-09-17 00:25:11,458:INFO:172.16.60.228:reading from: /opt/aeonztps/etc/configs/eos/all.conf
2016-09-17 00:25:11,458:INFO:172.16.60.228:pushing all config to device
2016-09-17 00:25:11,485:INFO:172.16.60.228:no model config file found: /opt/aeonztps/etc/configs/eos/vEOS.conf
Traceback (most recent call last):
  File "./eos-bootstrap", line 449, in <module>
    main()
  File "./eos-bootstrap", line 442, in main
    do_push_config(dev)
  File "./eos-bootstrap", line 252, in do_push_config
    dev.api.execute(['enable', 'copy running-config startup-config'])
  File "/usr/local/lib/python2.7/dist-packages/aeon/eos/connector.py", line 36, in execute
    raise CommandError(exc=exc, commands=commands)
aeon.exceptions.CommandError


```

**Comment by jpsenior** [comment] 2017-02-02 03:07
@acarpi - per our conversation on Slack, we may have run into this issue again (Two separate issues) - not enough diagnostic output, and The SSH connection itself to the device may be timing out.

**Comment by acarpi** [comment] 2017-02-04 00:53
if we simply don't wrap the self.eapi.execute with a try...except CommandError the stacktrace gives you more context.

> 2017-02-03 22:09:34,668:ERROR:172.20.231.5:stderr=Traceback (most recent call last):
>   File "/opt/aeonztps/bin/eos-bootstrap", line 448, in <module>
>     main()
>   File "/opt/aeonztps/bin/eos-bootstrap", line 441, in main
>     do_push_config(dev)
>   File "/opt/aeonztps/bin/eos-bootstrap", line 252, in do_push_config
>     dev.api.execute(['enable', 'copy running-config startup-config'])
>   File "/usr/local/lib/python2.7/dist-packages/aeon/eos/connector.py", line 38, in execute
>     got = self.eapi.execute(commands)
>   File "/usr/local/lib/python2.7/dist-packages/pyeapi/eapilib.py", line 475, in execute
>     response = self.send(request)
>   File "/usr/local/lib/python2.7/dist-packages/pyeapi/eapilib.py", line 396, in send
>     raise CommandError(code, msg, command_error=err, output=out)
> pyeapi.eapilib.CommandError: Error [1000]: CLI command 3 of 3 'copy running-config startup-config' failed: could not run command [Cannot copy to startup-config when ZeroTouch is enabled]

**Comment by acarpi** [comment] 2017-02-05 09:09
I kindly suggest in aeon/eos/connector.py:38, to not do this
```
        try:
            got = self.eapi.execute(commands)
        except Exception as exc:
            raise CommandError(exc=exc, commands=commands)
```

but simply raise the original exception removing the try...except envelope. I found the original exception to be more descriptive and helped me resolve the real underneath issue, for which I submitted already a PR. Thanks!

**Comment by jeremyschulman** [comment] 2017-02-05 20:38
@acarpi - thank you.  given you've submitted the PR, I will close this issue here.

**Closed by jeremyschulman** 2017-02-05 20:38 UTC
Labels: bug, EOS, P1

**Comment by acarpi** [comment] 2017-02-05 21:47
@jeremyschulman  the PR doesn't fix the issue in aeon/eos/connector.py:38,  but the root cause triggering this exception. CommandError still raises without providing details, but this issue should probably be moved to the aeon-venos project being connector.py part of that library?

**Comment by jeremyschulman** [comment] 2017-02-06 15:24
@acarpi - agreed.  I've asked @bobbywatson3 to resolve this in the aeon-venos repo.

**Comment by bobbywatson3** [comment] 2017-02-07 01:06
Resolved.
