### ISSUE TITLE
eos dns ztp issue

### ISSUE THREAD

**Issue by ericdong66** [Apstra/aeon-ztps#185] opened 2017-03-21 22:49 UTC
after zeon ztp, mgmt port is moved to mgmt vrf, but dns is still configured under default vrf.

**Comment by bobbywatson3** [comment] 2017-03-21 22:50
Thanks Eric. I'm going to open a PR tomorrow and I'll add the fix for this as well.

**Comment by ericdong66** [comment] 2017-03-21 23:16
I can work on it if you wish, but I need some guide about how to fix this,
and what kind of test I should run before submit PR, let me know, thanks

**Comment by bobbywatson3** [comment] 2017-03-22 01:27
The code for this is in ztp-scripts/ztp-eos.sh. Unfortunately, we don't have any unit tests for the bash scripts. What you could do is deploy an environment in slicer, copy over the new ztp-eos.sh with the fix to the aeon-ztps server, and run a slicer sanitize to see if the issue is resolved.

**Comment by ericdong66** [comment] 2017-03-22 04:52
sending a untested patch, run out of time to test and pull pr.

diff --git a/ztp-scripts/ztp-eos.sh b/ztp-scripts/ztp-eos.sh
index 9513d31..05ff4be 100755
--- a/ztp-scripts/ztp-eos.sh
+++ b/ztp-scripts/ztp-eos.sh
@@ -29,6 +29,7 @@ SERVER_PORT=8080
 # ----------------------------------------------------

 DHCP_SUCCESS=$(grep -m1 DHCP_SUCCESS /var/log/messages)
+NAME_SERVER=$(grep -m1 nameserver /var/log/messages)

 # example output:
 # ---------------
@@ -39,6 +40,7 @@ INTF=$(echo ${DHCP_SUCCESS} | gawk 'match($0, /received
on ([^ ]+)/,arr){ print
 IP_ADDR=$(echo ${DHCP_SUCCESS} | gawk 'match($0, /Ip Address:
([^;]+)/,arr){ print arr[1]}')
 GATEWAY=$(echo ${DHCP_SUCCESS} | gawk 'match($0, /Gateway: ([^;]+)/,arr){
print arr[1]}')
 BOOTFILE=$(echo ${DHCP_SUCCESS} | gawk 'match($0, /Boot File: ([^
]+)/,arr){ print arr[1]}')
+DNS_IP=$(echo ${NAME_SERVER} | gawk 'match($0, /nameserver ([^ ]+)#/,arr){
print arr[1]}')

 SERVER=$(echo ${BOOTFILE} | cut --delimiter=/ -f3)

@@ -73,6 +75,8 @@ ip route vrf management 0.0.0.0/0 $GATEWAY"
 fi

 ${CLI} "configure terminal
+no ip name-server vrf default
+ip name-server vrf management $DNS_IP
 interface $INTF
 vrf forwarding management
 ip address $IP_ADDR"
aeon-ztps develop %

**Comment by bobbywatson3** [comment] 2017-03-28 15:10
Thanks @ericdong66 , that patch worked.

**Closed** 2017-03-28 15:42 UTC
